import fs from 'node:fs';
import {build} from 'esbuild';
const revision=JSON.parse(fs.readFileSync('output/model-manifest.json','utf8')).sha256.slice(0,12);
const result=await build({entryPoints:['src/viewer.js'],bundle:true,write:false,format:'iife',minify:true,target:['chrome100'],legalComments:'inline',define:{__MODEL_REVISION__:JSON.stringify(revision)}});
const model=fs.readFileSync('output/house.glb').toString('base64');
const html=`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>王源東住宅 · 3D 概念模型</title><style>
:root{color-scheme:light;font-family:system-ui,-apple-system,"Microsoft JhengHei",sans-serif;color:#263a39;background:#f3ede2}*{box-sizing:border-box}body{margin:0;height:100dvh;overflow:hidden}header{height:62px;padding:12px 22px;border-bottom:1px solid #d9d7cc;display:flex;align-items:center;justify-content:space-between;gap:12px;background:#faf8f2}h1{font-size:18px;letter-spacing:.06em;margin:0}header small{display:block;color:#77827b;font-size:11px;font-weight:400;margin-top:3px}header a{font-size:12px;color:#31594e;text-decoration:none;border:1px solid #bac7be;border-radius:7px;padding:8px 12px;white-space:nowrap}main{height:calc(100dvh - 62px);display:grid;grid-template-columns:minmax(0,1fr) 278px}#stage{position:relative;overflow:hidden;min-height:0}canvas{width:100%;height:100%;display:block;touch-action:none}#controls{background:#faf8f2;border-left:1px solid #d9d7cc;padding:15px 16px;overflow:auto;overscroll-behavior:contain}.hv-section{border-bottom:1px solid #e3e3d8;padding:0 0 12px;margin-bottom:12px}.hv-section:last-child{border:0}.hv-section h3{font-size:12px;margin:0 0 8px;color:#68786e;font-weight:650;letter-spacing:.06em}.hv-row{display:flex;align-items:center;gap:8px;min-height:30px;font-size:13px;cursor:pointer}.hv-section:first-child{display:grid;grid-template-columns:1fr 1fr}.hv-section:first-child h3{grid-column:1/-1}input[type=checkbox]{width:17px;height:17px;accent-color:#376653;flex-shrink:0}input[type=range]{width:116px;accent-color:#376653;min-width:40px}select{border:1px solid #c8d0c7;background:white;border-radius:5px;padding:5px;color:#263a39}.hv-btn{background:#fff;border:1px solid #cbd3c9;color:#2d4f43;border-radius:6px;padding:8px 10px;margin:3px 5px 3px 0;font-size:12px;cursor:pointer;min-height:34px}.hv-btn:hover{background:#e4eee5}.hv-btn:focus-visible,input:focus-visible,select:focus-visible{outline:2px solid #477865;outline-offset:2px}.hv-room-label{font-size:12px;line-height:1.35;padding:4px 7px;background:#fffffff0;color:#23483b;border:1px solid #b5c6b6;border-radius:5px;box-shadow:0 2px 7px #243a2312}#status{position:absolute;bottom:12px;left:16px;font-size:11px;color:#65766d;pointer-events:none;max-width:90%;z-index:3;background:#faf8f2dd;padding:5px 8px;border-radius:4px}#status.error{color:#9d2c2c;background:#fff3ee}.hint{position:absolute;left:16px;top:14px;color:#68766b;font-size:11px;pointer-events:none;line-height:1.65;z-index:2}.badge{display:inline-block;border:1px solid #d2d6c9;border-radius:20px;padding:2px 8px;margin-bottom:5px;background:#f8f7edcc;font-size:10px;letter-spacing:.06em}
@media(max-width:700px){header{height:55px;padding:8px 13px}h1{font-size:15px}header small{font-size:10px}main{height:calc(100dvh - 55px);grid-template-columns:1fr;grid-template-rows:minmax(0,61%) minmax(0,39%)}#controls{border-left:0;border-top:1px solid #d9d7cc;padding:10px 14px;display:grid;grid-template-columns:1fr 1fr;gap:8px 16px;align-content:start}.hv-section{margin:0;padding-bottom:8px}.hv-section h3{font-size:11px}.hv-row{font-size:12px;min-height:31px}.hv-btn{padding:7px 8px;font-size:11px;margin:2px 3px 2px 0}#status{bottom:7px;left:8px;font-size:10px}.hint{left:10px;top:9px;font-size:10px}.hv-room-label{font-size:10px;padding:2px 4px}}
</style></head><body><header><h1>王源東住宅<small>3D 概念模型 · 依確認之請照圖</small></h1><a id="download" download="house.glb">下載 GLB</a></header><main><section id="stage" aria-label="住宅三維模型"><canvas id="canvas" aria-label="單指旋轉，雙指縮放與移動"></canvas><div class="hint"><span class="badge">CONCEPT MODEL</span><br>單指旋轉 · 雙指縮放／移動<br>點「只看」切換室內視圖</div><div id="status" role="status">正在載入模型…</div></section><aside id="controls" aria-label="模型觀看控制"></aside></main><script id="model-data" type="application/octet-stream">${model}</script><script>document.getElementById('download').href='data:model/gltf-binary;base64,'+document.getElementById('model-data').textContent.trim();</script><script>${result.outputFiles[0].text.replaceAll('</script','<\\/script')}</script></body></html>`;
const styles=['bohemian','industrial','eclectic','wabisabi'];
const styleTags=styles.map(s=>`<script id="model-${s}" type="application/octet-stream">${fs.readFileSync(`output/styles/${s}.glb`).toString('base64')}</script>`).join('');
const styledHtml=html.replace('</head>','<style>.hv-style{display:block!important;grid-column:1/-1}.hv-style select{width:100%;min-height:40px;font-size:14px;margin-bottom:6px}.hv-groups{display:grid;grid-template-columns:1fr 1fr}.hv-groups h3{grid-column:1/-1}.hv-style .hv-btn{width:100%}</style></head>').replace('點「只看」切換室內視圖','先選風格，再點「只看」查看家具');
fs.writeFileSync('output/住宅3D檢視器.html',styledHtml.replace('<script id="model-data"',styleTags+'<script id="model-data"'));
fs.writeFileSync('output/index.html',styledHtml);
console.log(JSON.stringify({onlineBytes:Buffer.byteLength(styledHtml),offlineBytes:fs.statSync('output/住宅3D檢視器.html').size,bundleBytes:result.outputFiles[0].contents.length}));
