import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import validator from 'gltf-validator';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/t88510/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const bytes=fs.readFileSync('output/house.glb');
const result=await validator.validateBytes(new Uint8Array(bytes),{uri:'house.glb',maxIssues:100});
fs.writeFileSync('output/glb-validation.json',JSON.stringify(result,null,2));
console.log('GLB',JSON.stringify({errors:result.issues.numErrors,warnings:result.issues.numWarnings,hints:result.issues.numHints}));
const browser=await chromium.launch({headless:true,channel:'msedge',args:['--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1280,height:900}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const network=[];page.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url())});
await page.goto(pathToFileURL(path.resolve('output/住宅3D檢視器.html')).href);
await page.waitForFunction(()=>window.houseViewer?.gltf,{timeout:60000});
await page.waitForTimeout(900);
fs.mkdirSync('output/previews',{recursive:true});
await page.screenshot({path:'output/previews/exterior.png'});
const base=await page.evaluate(()=>({status:document.querySelector('#status').textContent,groups:['SITE','FLOOR_1','FLOOR_2','FLOOR_3','FLOOR_4','ROOF'].map(n=>({name:n,visible:window.houseViewer.gltf.scene.getObjectByName(n)?.visible})),perspective:window.houseViewer.camera.isPerspectiveCamera,rooms:window.houseViewer.gltf.scene.getObjectsByProperty('type','Object3D').filter(x=>x.name.startsWith('ROOM_')).length}));
const tests=[];
for(const [i,word] of ['一','二','三','四'].entries()){
 await page.getByRole('button',{name:`只看${word}樓`,exact:true}).click();
 await page.waitForTimeout(350);
 tests.push(await page.evaluate(()=>({visible:['FLOOR_1','FLOOR_2','FLOOR_3','FLOOR_4','ROOF'].filter(n=>window.houseViewer.gltf.scene.getObjectByName(n).visible),labels:[...document.querySelectorAll('.hv-room-label')].filter(e=>e.style.display==='block').length,clippedMeshes:window.houseViewer.gltf.scene.getObjectsByProperty('type','Mesh').filter(m=>m.material.clippingPlanes?.length).length})));
 await page.screenshot({path:`output/previews/floor-${i+1}.png`});
}
await page.getByRole('button',{name:'顯示全部',exact:true}).click();
await page.locator('#hv-grp-ROOF').uncheck();
const roofHidden=await page.evaluate(()=>!window.houseViewer.gltf.scene.getObjectByName('ROOF').visible);
await page.locator('#hv-grp-ROOF').check();
const before=await page.evaluate(()=>window.houseViewer.camera.position.toArray());
await page.mouse.move(440,370);await page.mouse.wheel(0,-250);await page.waitForTimeout(300);
const after=await page.evaluate(()=>window.houseViewer.camera.position.toArray());
await page.mouse.move(430,360);await page.mouse.down();await page.mouse.move(560,395,{steps:8});await page.mouse.up();await page.waitForTimeout(300);
const rotated=await page.evaluate(()=>window.houseViewer.camera.position.toArray());
await page.setViewportSize({width:412,height:915});
await page.getByRole('button',{name:'重設視角',exact:true}).click();
await page.waitForTimeout(500);await page.screenshot({path:'output/previews/mobile-layout.png'});
const mobile=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,width:innerWidth,canvas:[document.querySelector('#canvas').clientWidth,document.querySelector('#canvas').clientHeight]}));
const cdp=await context.newCDPSession(page);
const touchBefore=await page.evaluate(()=>window.houseViewer.camera.position.toArray());
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:280}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:245,y:300}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250);
const touchAfter=await page.evaluate(()=>window.houseViewer.camera.position.toArray());
const pinchBefore=await page.evaluate(()=>window.houseViewer.camera.position.distanceTo(window.houseViewer.controls.target));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:160,y:300,id:1},{x:250,y:300,id:2}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:110,y:300,id:1},{x:300,y:300,id:2}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250);
const pinchAfter=await page.evaluate(()=>window.houseViewer.camera.position.distanceTo(window.houseViewer.controls.target));
const report={glbErrors:result.issues.numErrors,glbWarnings:result.issues.numWarnings,glbHints:result.issues.numHints,base,floorTests:tests,roofHidden,zoomChanged:JSON.stringify(before)!==JSON.stringify(after),rotationChanged:JSON.stringify(after)!==JSON.stringify(rotated),touchRotationChanged:JSON.stringify(touchBefore)!==JSON.stringify(touchAfter),pinchZoomChanged:Math.abs(pinchBefore-pinchAfter)>.01,mobile,errors,externalNetworkRequests:network,androidPhysicalDeviceTested:false};
fs.writeFileSync('output/viewer-validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
await browser.close();
if(result.issues.numErrors||errors.length||network.length||!roofHidden||tests.some((t,i)=>t.visible.join()!==`FLOOR_${i+1}`||!t.labels||!t.clippedMeshes))process.exitCode=1;
